version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4
parameters:
  sfdx_version:
    description: |
      By default, the latest version of the standalone CLI will be installed.
      To install via npm, supply a version tag such as "latest" or "6".
    default: ''
    type: string
  repo_tag:
    description: "The tag of the module repo to checkout, '' defaults to branch/PR"
    default: ''
    type: string
  workflow:
    description: |
      String that controls which workflow would run.

      This parameter is used by automation to determine if a workflow will run
      within a pipeline.
    type: string
    default: 'test-and-release'
workflows:
  test-and-release:
    when:
      equal: [test-and-release, << pipeline.parameters.workflow >>]
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/test-package:
          matrix:
            parameters:
              os:
                - linux
                - windows
              node_version:
                - latest
                - lts
                - maintenance
      - release-management/test-nut:
          matrix:
            parameters:
              os:
                - linux
                - windows
              sfdx_version:
                - latest
              node_version:
                - latest
          requires:
            - release-management/test-package
          context:
            - na40-jwt
            - na40-auth-url
      - release-management/release-package:
          context:
            - AWS
            - release
          sign: true
          github-release: true
          requires:
            - release-management/test-package
          filters:
            branches:
              only: main
  test-ts-update:
    when:
      equal: [test-ts-update, << pipeline.parameters.workflow >>]
    jobs:
      - release-management/test-ts-update:
          es_target: ES2021
  just-nuts:
    when:
      equal: [just-nuts, << pipeline.parameters.workflow >>]
    jobs:
      - release-management/test-nut:
          name: just-nuts-<< matrix.os >>
          sfdx_version: << pipeline.parameters.sfdx_version >>
          sfdx_executable_path: sfdx
          repo_tag: << pipeline.parameters.repo_tag >>
          matrix:
            parameters:
              os:
                - linux
                - windows
          context:
            - na40-jwt
            - na40-auth-url
  dependabot-automerge:
    when:
      equal: [dependabot-automerge, << pipeline.parameters.workflow >>]
    jobs:
      - release-management/dependabot-automerge:
          context: release
